import { AGENT_CATEGORIES, AGENT_TOOL_IDS, ROLE_LEVEL } from './constants.js';

/**
 * Catálogo de facultades del agente — revisar antes de integrar en producción.
 * status: planned | ready | disabled
 */
export const AGENT_FACULTIES = [
  {
    id: AGENT_TOOL_IDS.HELP_GUIDE,
    category: AGENT_CATEGORIES.SYSTEM,
    nameEs: 'Ayuda y guías',
    nameEn: 'Help & how-to guides',
    descriptionEs: 'Explica cómo cobrar, agendar, buscar pacientes y más.',
    // Any authenticated staff (incl. unresolved role → 99) can ask how-to.
    minLevel: ROLE_LEVEL.GUEST,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.SEARCH_PATIENT,
    category: AGENT_CATEGORIES.PATIENTS,
    nameEs: 'Buscar paciente',
    nameEn: 'Search patient',
    descriptionEs: 'Busca por nombre o teléfono en la clínica activa.',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_TODAY_SCHEDULE,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Ver agenda del día',
    nameEn: 'View day schedule',
    descriptionEs: 'Lista citas de una fecha y sede (solo clínicas permitidas).',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_APPOINTMENT,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Ver detalle de cita',
    nameEn: 'View appointment',
    descriptionEs: 'Muestra paciente, hora, equipo y estatus de una cita.',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.CHECK_AVAILABILITY,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Consultar disponibilidad',
    nameEn: 'Check availability',
    descriptionEs: 'Huecos libres por fecha, equipo y duración.',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.BOOK_APPOINTMENT,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Agendar cita',
    nameEn: 'Book appointment',
    descriptionEs: 'Crea cita validando horario, equipo y paciente (mismas reglas que staff).',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.UPDATE_APPOINTMENT_NOTES,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Actualizar notas de cita',
    nameEn: 'Update appointment notes',
    descriptionEs: 'Edita notas del día sin cambiar horario ni equipo.',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.CANCEL_APPOINTMENT,
    category: AGENT_CATEGORIES.SCHEDULE,
    nameEs: 'Cancelar cita',
    nameEn: 'Cancel appointment',
    descriptionEs: 'Marca cita como cancelada (confirmación requerida).',
    minLevel: ROLE_LEVEL.STAFF,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_DAY_REPORT,
    category: AGENT_CATEGORIES.REPORTS,
    nameEs: 'Reporte del día',
    nameEn: 'Day report',
    descriptionEs: 'Citas atendidas y estatus por fecha.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_SALES_REPORT,
    category: AGENT_CATEGORIES.REPORTS,
    nameEs: 'Reporte de ventas',
    nameEn: 'Sales report',
    descriptionEs: 'Ventas, tickets y montos — bloqueado para staff básico.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_BLACK_BOX,
    category: AGENT_CATEGORIES.REPORTS,
    nameEs: 'Caja negra / auditoría',
    nameEn: 'Black box audit',
    descriptionEs: 'Bitácora de movimientos sensibles.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_PATIENT_LEDGER,
    category: AGENT_CATEGORIES.REPORTS,
    nameEs: 'Libro mayor del paciente',
    nameEn: 'Patient ledger',
    descriptionEs: 'Historial de ventas y sesiones de un paciente.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'ready',
  },
  {
    id: AGENT_TOOL_IDS.MANAGE_BLOCKED_SLOTS,
    category: AGENT_CATEGORIES.ADMIN,
    nameEs: 'Gestionar bloqueos de agenda',
    nameEn: 'Manage blocked slots',
    descriptionEs: 'Crear o quitar bloqueos de horario.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'planned',
  },
  {
    id: AGENT_TOOL_IDS.MANAGE_SERVICES,
    category: AGENT_CATEGORIES.ADMIN,
    nameEs: 'Gestionar servicios / cámaras',
    nameEn: 'Manage services',
    descriptionEs: 'Catálogo de equipos y duraciones.',
    minLevel: ROLE_LEVEL.MANAGER,
    masterOnly: false,
    status: 'planned',
  },
  {
    id: AGENT_TOOL_IDS.MANAGE_STAFF,
    category: AGENT_CATEGORIES.ADMIN,
    nameEs: 'Gestionar usuarios staff',
    nameEn: 'Manage staff users',
    descriptionEs: 'Altas, bajas y PIN de personal.',
    minLevel: ROLE_LEVEL.MASTER,
    masterOnly: true,
    status: 'planned',
  },
  {
    id: AGENT_TOOL_IDS.MANAGE_ROLES,
    category: AGENT_CATEGORIES.ADMIN,
    nameEs: 'Gestionar roles y niveles',
    nameEn: 'Manage roles',
    descriptionEs: 'Define niveles de acceso por rol.',
    minLevel: ROLE_LEVEL.MASTER,
    masterOnly: true,
    status: 'planned',
  },
  {
    id: AGENT_TOOL_IDS.VIEW_COMPANY_CONFIG,
    category: AGENT_CATEGORIES.ADMIN,
    nameEs: 'Ver configuración de clínica',
    nameEn: 'View clinic config',
    descriptionEs: 'Datos de empresa, mensajes y ajustes (sin exponer secretos).',
    minLevel: ROLE_LEVEL.MASTER,
    masterOnly: true,
    status: 'planned',
  },
  {
    id: AGENT_TOOL_IDS.RUN_DESIGN_AUDIT,
    category: AGENT_CATEGORIES.SYSTEM,
    nameEs: 'Auditoría de diseño del sistema',
    nameEn: 'System design audit',
    descriptionEs: 'Detecta huecos de permisos y riesgos; notifica solo al maestro.',
    minLevel: ROLE_LEVEL.MASTER,
    masterOnly: true,
    status: 'ready',
  },
];

export function listFacultiesForLevel(roleLevel) {
  return AGENT_FACULTIES.filter((f) => {
    if (f.status === 'disabled') return false;
    if (f.masterOnly) return roleLevel <= ROLE_LEVEL.MASTER;
    return roleLevel <= (f.minLevel ?? ROLE_LEVEL.STAFF);
  });
}

export function summarizeFaculties(locale = 'es') {
  return AGENT_FACULTIES.map((f) => ({
    id: f.id,
    category: f.category,
    name: locale === 'en' ? f.nameEn : f.nameEs,
    description: locale === 'en' ? f.descriptionEs : f.descriptionEs,
    minLevel: f.minLevel,
    masterOnly: f.masterOnly,
    status: f.status,
  }));
}
